version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db_amde
    restart: always
    environment:
      POSTGRES_DB: gestao_clinica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_amde
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@amde.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  pgdata:
